update: gitlab-ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,122 +1,112 @@
-# This file is a template, and might need editing before it works on your project.
-# To contribute improvements to CI/CD templates, please follow the Development guide at:
-# https://docs.gitlab.com/ee/development/cicd/templates.html
-# This specific template is located at:
-# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml
+image: docker:26.1.3
 
-# Build a Docker image with CI/CD and push to the GitLab registry.
-# Docker-in-Docker documentation: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
-#
-# This template uses one generic job with conditional builds
-# for the default branch and all other (MR) branches.
-#
-image: docker:20.10.16
+services:
+  - docker:26.1.3-dind
+
+variables:
+  DOCKER_HOST: tcp://docker:2375
+  DOCKER_TLS_CERTDIR: ""
+  DOCKER_BUILDKIT: "1"
+  IMAGE_TAG: "$CI_COMMIT_SHA"
+  BRANCH_TAG: "$CI_COMMIT_REF_SLUG"
+  APP_IMAGE: "$CI_REGISTRY_IMAGE/app"
+  PORTAL_IMAGE: "$CI_REGISTRY_IMAGE/portal"
+  FREESWITCH_IMAGE: "$CI_REGISTRY_IMAGE/freeswitch"
+  COMPOSE_FILE: docker-compose.build.yml
+
 stages:
-  - 'build'
-  - 'push'
-  - 'webhook'
-  - 'update-manifest-development'
+  - build
+  - tag
+  - webhook
+  - update-manifest-development
 
-# This folder is cached between builds
-# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
 default:
-  services:
-    - docker:20.10.16-dind
+  before_script:
+    - apk add --no-cache curl
+    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
 
-before_script:
-  - export IMAGE_NAME_WITH_REGISTRY_PREFIX=$CI_REGISTRY_IMAGE # Your repository prefixed with GitLab Registry URL
-  - export COMMIT_HASH=$CI_COMMIT_SHA # Your current commit sha
-  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
-  - apk add --update curl && rm -rf /var/cache/apk/*
-  - export CONTAINER_FULL_IMAGE_NAME=$IMAGE_NAME_WITH_REGISTRY_PREFIX/$CI_COMMIT_REF_NAME
-  - export CONTAINER_FULL_IMAGE_NAME_WITH_TAG=$CONTAINER_FULL_IMAGE_NAME:$COMMIT_HASH
-docker-build:
+compose-build:
   stage: build
-  # Default branch leaves tag empty (= latest tag)
-  # All other branches are tagged with the escaped branch name (commit ref slug)
-  #
-  only:
-    - development
-    - master
   script:
-    - |
-      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
-        tag=""
-        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
-      else
-        tag="$CI_COMMIT_REF_SLUG.$CI_COMMIT_SHA"
-        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
-      fi
-    - docker build --pull -t "${CONTAINER_FULL_IMAGE_NAME_WITH_TAG}" .
-    - docker push "${CONTAINER_FULL_IMAGE_NAME_WITH_TAG}"
+    - test -n "$FS_TOKEN" || (echo "FS_TOKEN variable is required" && exit 1)
+    - docker compose build --pull
+    - docker compose push
+  rules:
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+    - if: '$CI_COMMIT_BRANCH'
 
 push-latest:
-  variables:
-    GIT_STRATEGY: none
-  stage: push
-  only:
-    - master
-    - development
-  script:
-    - docker pull $CONTAINER_FULL_IMAGE_NAME_WITH_TAG
-    - docker tag $CONTAINER_FULL_IMAGE_NAME_WITH_TAG $CONTAINER_FULL_IMAGE_NAME:latest
-    - docker push $CONTAINER_FULL_IMAGE_NAME:latest
-
-push-tag:
-  variables:
-    GIT_STRATEGY: none
-  stage: push
+  stage: tag
+  needs:
+    - compose-build
   rules:
-    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+)*$/' # Regex for semantic versioning tags
+    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
   script:
-    - docker pull $CONTAINER_FULL_IMAGE_NAME_WITH_TAG || true
-    - docker tag $CONTAINER_FULL_IMAGE_NAME_WITH_TAG $CONTAINER_FULL_IMAGE_NAME:$CI_COMMIT_TAG
-    - docker push $CONTAINER_FULL_IMAGE_NAME:$CI_COMMIT_TAG
+    - for service in app portal freeswitch; do
+        SOURCE_IMAGE="$CI_REGISTRY_IMAGE/$service:${IMAGE_TAG}";
+        TARGET_IMAGE="$CI_REGISTRY_IMAGE/$service:latest";
+        docker pull "$SOURCE_IMAGE";
+        docker tag "$SOURCE_IMAGE" "$TARGET_IMAGE";
+        docker push "$TARGET_IMAGE";
+      done
 
-# webhook:
-#   stage: webhook
-#   only:
-#     - development
-#   script:
-#     - echo "CI_COMMIT_TAG=${CI_COMMIT_TAG}"
-#     - curl --request POST "${DEV_WEBHOOK_URL}?tag=${CI_COMMIT_TAG}"
+push-branch-tag:
+  stage: tag
+  needs:
+    - compose-build
+  rules:
+    - if: '$CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
+  script:
+    - for service in app portal freeswitch; do
+        SOURCE_IMAGE="$CI_REGISTRY_IMAGE/$service:${IMAGE_TAG}";
+        TARGET_IMAGE="$CI_REGISTRY_IMAGE/$service:${BRANCH_TAG}";
+        docker pull "$SOURCE_IMAGE";
+        docker tag "$SOURCE_IMAGE" "$TARGET_IMAGE";
+        docker push "$TARGET_IMAGE";
+      done
 
+push-release-tag:
+  stage: tag
+  needs:
+    - compose-build
+  rules:
+    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+(\.[0-9]+)*$/'
+  script:
+    - for service in app portal freeswitch; do
+        SOURCE_IMAGE="$CI_REGISTRY_IMAGE/$service:${IMAGE_TAG}";
+        TARGET_IMAGE="$CI_REGISTRY_IMAGE/$service:$CI_COMMIT_TAG";
+        docker pull "$SOURCE_IMAGE";
+        docker tag "$SOURCE_IMAGE" "$TARGET_IMAGE";
+        docker push "$TARGET_IMAGE";
+      done
 
 webhook:
   stage: webhook
-  only:
-    - development
+  needs:
+    - compose-build
+  rules:
+    - if: '$CI_COMMIT_BRANCH == "development"'
   script:
-    - echo "Deploying to $CAPROVER_APP_NAME with image $CONTAINER_FULL_IMAGE_NAME_WITH_TAG"
-    - docker run caprover/cli-caprover:2.2.3 caprover deploy --appToken $CAPROVER_APP_TOKEN --caproverUrl $CAPROVER_URL --imageName $CONTAINER_FULL_IMAGE_NAME_WITH_TAG --appName $CAPROVER_APP_NAME
-
+    - DEPLOY_IMAGE="$APP_IMAGE:${IMAGE_TAG}"
+    - echo "Deploying $DEPLOY_IMAGE to CapRover app $CAPROVER_APP_NAME"
+    - docker run --rm caprover/cli-caprover:2.2.3 caprover deploy --appToken "$CAPROVER_APP_TOKEN" --caproverUrl "$CAPROVER_URL" --imageName "$DEPLOY_IMAGE" --appName "$CAPROVER_APP_NAME"
 
 update-manifest-development:
   stage: update-manifest-development
-  only:
-    - development
+  needs:
+    - compose-build
+  rules:
+    - if: '$CI_COMMIT_BRANCH == "development"'
   variables:
     GIT_REPO: "https://gitlab.com/vqtuan96/vill-k8s-configs.git"
     APP_FOLDER: "helm-dispatcher"
   script:
-    - |
-      echo "Updating manifest for development"
-      echo "install git"
-      apk add --update git && rm -rf /var/cache/apk/*
-      echo "clone config repo"
-      touch ~/.gitconfig
-      git config --global user.username $GITLAB_CONFIG_USERNAME
-      git config --global user.password $GITLAB_CONFIG_PASSWORD
-      git config --global user.email "vqtuan96@gmail.com"
-      git config --global user.name "vo quoc tuan"
-      echo "get git config"
-      git config --list
-      git clone https://$GITLAB_CONFIG_USERNAME:$GITLAB_CONFIG_PASSWORD@gitlab.com/vqtuan96/vill-k8s-configs.git config
-      cd config/$APP_FOLDER
-      ls -la
-      echo "update image tag"
-      sed -i "s/tag:.*/tag: $COMMIT_HASH/g" values.yaml
-      git add .
-      git commit -m "update image tag to $HASH_COMMIT"
-      git remote set-url origin https://$GITLAB_CONFIG_USERNAME:$GITLAB_CONFIG_PASSWORD@gitlab.com/vqtuan96/vill-k8s-configs.git
-      git push origin main
+    - apk add --no-cache git
+    - git config --global user.name "vo quoc tuan"
+    - git config --global user.email "vqtuan96@gmail.com"
+    - git clone "https://$GITLAB_CONFIG_USERNAME:$GITLAB_CONFIG_PASSWORD@gitlab.com/vqtuan96/vill-k8s-configs.git" config
+    - cd config/$APP_FOLDER
+    - sed -i "s/tag:.*/tag: ${IMAGE_TAG}/g" values.yaml
+    - git add values.yaml
+    - git commit -m "ci: update image tag to ${IMAGE_TAG}" || echo "No changes to commit"
+    - git push origin main
